tasks/task-12: Fixed bugs
AlexAnoschenko/PropertyCross pull request #31
Opened 2019-10-16 11:15 UTC by AlexAnoschenko

2019-10-16 11:53 UTC, kkamik commented on src/components/SearchPage/InputAdress/InputAdress.scss
> +    width: 12%;
это странно, можешь отхватить в будущем от этого.

2019-10-16 11:54 UTC, kkamik commented on src/components/SearchPage/InputAdress/InputAdressPure.jsx
> +        if (this.state.inputText === '') {
this.state.inputText используется 2 раза, можно сделать деструктуризацию.

2019-10-16 11:54 UTC, kkamik commented on src/components/SearchPage/InputAdress/InputAdressPure.jsx
> +import styles from './InputAdress.scss';
scss???? у нас sass подключен?)

2019-10-16 11:54 UTC, kkamik commented on src/components/SearchPage/Overview/Overview.jsx
> +import styles from './Overview.scss';
и тут scss

2019-10-16 11:55 UTC, kkamik commented on src/components/SearchPage/Overview/Overview.scss
> +    width: 12%;
и тут, как начнешь делать верстку и для мобилы и для десктопа, скорее всего отхватишь проблем.

2019-10-16 11:55 UTC, kkamik commented on src/components/SearchPage/RecentSearchList/RecentSearchList.scss
> +    width: 12%;
и тут

2019-10-16 11:55 UTC, kkamik commented on src/components/SearchPage/RecentSearchList/RecentSearchList.scss
> +    width: 12%;
и тут

2019-10-16 11:57 UTC, kkamik commented on src/components/SearchPage/SearchPagePure.jsx
> +                    onSubmitError={this.onSubmitError}
зачем новый обработчик прокидывать, если ты можешь ошибку в this.handleSubmit словить?

2019-10-17 09:06 UTC, AlexAnoschenko commented on src/components/SearchPage/InputAdress/InputAdress.scss
> +    width: 12%;
Исправил

2019-10-17 09:07 UTC, AlexAnoschenko commented on src/components/SearchPage/InputAdress/InputAdressPure.jsx
> +import styles from './InputAdress.scss';
Исправил

2019-10-17 09:07 UTC, AlexAnoschenko commented on src/components/SearchPage/Overview/Overview.jsx
> +import styles from './Overview.scss';
Исправил

2019-10-17 09:07 UTC, AlexAnoschenko commented on src/components/SearchPage/Overview/Overview.scss
> +    width: 12%;
Исправил

2019-10-17 09:07 UTC, AlexAnoschenko commented on src/components/SearchPage/RecentSearchList/RecentSearchList.scss
> +    width: 12%;
Исправил

2019-10-17 09:07 UTC, AlexAnoschenko commented on src/components/SearchPage/RecentSearchList/RecentSearchList.scss
> +    width: 12%;
Исправил

2019-10-17 09:20 UTC, AlexAnoschenko commented on src/components/SearchPage/InputAdress/InputAdressPure.jsx
> +        if (this.state.inputText === '') {
Исправил

2019-10-17 11:24 UTC, AlexAnoschenko commented on src/components/SearchPage/SearchPagePure.jsx
> +                    onSubmitError={this.onSubmitError}
Решили оставить как есть

2019-10-17 11:25 UTC, kkamik commented on src/components/SearchPage/InputAdress/InputAdress.css
> +::placeholder {
::placeholder что это?

2019-10-17 11:26 UTC, kkamik commented on src/components/SearchPage/RecentSearchList/RecentSearchListPure.jsx
> +                                onClick={() => this.moveElement(item, index)}
handleRecentRequestClick

ты тут ничего не двигаешь.

2019-10-17 11:28 UTC, kkamik commented on src/components/SearchPage/RecentSearchList/RecentSearchListPure.jsx
> +        this.props.recentRequests.splice(0, 0, this.props.recentRequests.splice(index, 1)[0]);
![image](https://user-images.githubusercontent.com/11601969/67005002-38f36700-f0ea-11e9-81e8-10ba639a1c99.png)

Мутировать данные фигово. Потом баги появляются в самых неожиданных местах. Прочитай про имьютабельность и переделай это.

2019-10-17 11:30 UTC, kkamik commented on src/components/Wrapper/Wrapper.module.css
> +@value tablet: 641px;
эти штуки должны лежать в файле с переменными, а не в файле со стилями wrapper'a

2019-10-17 13:29 UTC, AlexAnoschenko commented on src/components/SearchPage/InputAdress/InputAdress.css
> +::placeholder {
Удалил

2019-10-17 13:29 UTC, AlexAnoschenko commented on src/components/SearchPage/RecentSearchList/RecentSearchListPure.jsx
> +                                onClick={() => this.moveElement(item, index)}
Исправил

2019-10-17 13:29 UTC, AlexAnoschenko commented on src/components/Wrapper/Wrapper.module.css
> +@value tablet: 641px;
Исправил

2019-10-17 13:29 UTC, AlexAnoschenko commented on src/components/SearchPage/RecentSearchList/RecentSearchListPure.jsx
> +        this.props.recentRequests.splice(0, 0, this.props.recentRequests.splice(index, 1)[0]);
Исправил

2019-10-17 13:32 UTC, kkamik requested changes

2019-10-17 13:32 UTC, kkamik commented on src/components/ApartmentsPage/ApartmentsPagePure.jsx
> +                        console.log('123');
?????

2019-10-17 13:32 UTC, kkamik commented on src/components/SearchPage/RecentSearchList/RecentSearchListPure.jsx
> +        const sortedReecentRequests = recentRequests.sort(
Reecent

2019-10-17 13:32 UTC, kkamik commented on src/components/SearchPage/RecentSearchList/RecentSearchListPure.jsx
> +            this.setState({
в случае ошибки ничего не надо делать?

2019-10-17 13:32 UTC, kkamik commented on src/components/Wrapper/Wrapper.module.css
> +    margin-left: 5%;
опять какой-то прикол в процентах. Убери это.

2019-10-17 13:52 UTC, AlexAnoschenko commented on src/components/ApartmentsPage/ApartmentsPagePure.jsx
> +                        console.log('123');
Удалил

2019-10-17 13:52 UTC, AlexAnoschenko commented on src/components/SearchPage/RecentSearchList/RecentSearchListPure.jsx
> +        const sortedReecentRequests = recentRequests.sort(
Исправил

2019-10-17 13:52 UTC, AlexAnoschenko commented on src/components/SearchPage/RecentSearchList/RecentSearchListPure.jsx
> +            this.setState({
Сделал

2019-10-17 13:52 UTC, AlexAnoschenko commented on src/components/Wrapper/Wrapper.module.css
> +    margin-left: 5%;
Исправил

2019-10-17 14:15 UTC, kkamik commented on src/components/Wrapper/Wrapper.module.css
> +        margin-left: 400px;
зачем такие дикие отступы? Почему нельзя сделать max-width у контейнера?

2019-10-17 14:39 UTC, AlexAnoschenko commented on src/components/Wrapper/Wrapper.module.css
> +        margin-left: 400px;
Исправил

2019-10-17 18:09 UTC, kkamik commented on src/components/SearchPage/InputAdress/InputAdressPure.jsx
> +                    placeholder="London"
почему London?

2019-10-17 18:10 UTC, kkamik commented on src/components/SearchPage/InputAdress/InputAdressPure.jsx
> +                    <button className={styles.buttons} type="button" onClick={this.onSubmit}>
почему у <button /> класс buttons, а не button?

2019-10-18 06:27 UTC, AlexAnoschenko commented on src/components/SearchPage/InputAdress/InputAdressPure.jsx
> +                    placeholder="London"
Исправил

2019-10-18 06:27 UTC, AlexAnoschenko commented on src/components/SearchPage/InputAdress/InputAdressPure.jsx
> +                    <button className={styles.buttons} type="button" onClick={this.onSubmit}>
Исправил

2019-10-18 06:51 UTC, kkamik approved these changes

2019-10-18 07:09 UTC, merged